DROP TABLE IF EXISTS posts;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    adress TEXT NOT NULL
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);